services:
  mongo-fpos-container:
    image: mongo:6.0
    container_name: fpos_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-fpos-data:/data/db
  
  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fpos_backend
    depends_on:
      - mongo-fpos-container
    ports:
      - "3000:3000"
    environment:
      SPRING_DATA_MONGODB_URI: mongodb://mongo-fpos-container:27017/fpos
      JWT_SECRET_KEY: j7Giyh4FSAYNCUf4Ac0ZX2zCGcwSoD+PDE3kWMoBRf8=
      SUS_EMAIL_USERNAME: notifications.sus@gmail.com
      SUS_EMAIL_PASSWORD: kczq uvsc kujn nnnr
      FPOS_BACK_PORT: 3000
    volumes:
      - "./src/main/resources/templates:/src/main/resources/templates"

volumes:
  mongo-fpos-data:
  sus-back-data:
